openapi: '3.0.0'
info:
  title: 'Equinity-data-api'
  version: '1.0.0'
paths:
  /equinity/tasks/{id}:
    get:
      tags:
        - tasks
      summary: 'Get Task'
      operationId: 'getTask'
      parameters:
        - name: 'id'
          in: 'path'
          required: true
          schema:
            type: number
            example: '3456'
      responses:
        '200':
          description: 'Successful operation'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TaskDetails"
        '400':
          description: 'Bad request'
        '401':
          description: 'Unauthorized'
        '404':
          description: 'Not found'
        '500':
          description: 'Internal server error'

components:
  schemas:
    TaskDetails:
      type: 'object'
      properties:
        typeId:
          type: number
        stateId:
          type: number
        currentParticipant:
          type: 'string'