name: 'Build App with Gradle'
description: 'This action builds application jar using Gradle'
inputs:
  ## Used to capture the intial values before they get overwritten
  action_ref:
    description: "Capture the starting value of github.action_ref. DO NOT SET"
    default: ${{ github.action_ref }}
  action_repository:
    description: "Capture the starting value of github.action_repository. DO NOT SET"
    default: ${{ github.action_repository }}
  java-version:
    required: true
    type: string
  java-dist:
    required: true
    type: string
  working-directory:
    required: true
    type: string
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
      with:
        repository: ${{ inputs.action_repository }}
        ref: ${{ inputs.action_ref }}

    - name: Set up JDK ${{inputs.java-version}}
      uses: actions/setup-java@v4
      with:
        java-version: ${{inputs.java-version}}
        distribution: ${{inputs.java-dist}}

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        build-root-directory: ${{inputs.working-directory}}

    - name: Build and install dependencies
      uses: gradle/gradle-build-action@v2
      with:
        arguments: clean build
        build-root-directory: ${{inputs.working-directory}}
