{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress
  namespace: "{{ .Chart.Name }}-{{ .Values.service.environment }}"
  labels:
    {{- include "laa-crime-equinity-historical-data.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: "{{ $.Chart.Name }}-{{ $.Values.service.environment }}.{{ .host }}"
      http:
        paths:
          {{- range .paths }}
          - path: {{ . }}
            pathType: "ImplementationSpecific"
            backend:
              service:
                name: {{ $.Chart.Name }}
                port:
                  number: {{ $.Values.service.port }}
          - path: {{ $.Values.actuator.health.path }}
            pathType: "Exact"
            backend:
              service:
                name: {{ $.Chart.Name }}
                port:
                  number: {{ $.Values.actuator.port }}
          {{- end }}
    {{- end }}
{{- end }}
