{{- if .Values.actuator.metrics.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Chart.Name }}-monitoring
  labels:
    {{- include "laa-crime-equinity-historical-data.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "laa-crime-equinity-historical-data.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            component: monitoring
{{- end }}