{{- $appName := include "laa-crime-equinity-historical-data.fullname" . -}}
{{- $envName := $.Values.service.environment -}}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "laa-crime-equinity-historical-data.fullname" . }}
  namespace: "{{ $appName }}-{{ $envName }}"
  labels:
    {{- include "laa-crime-equinity-historical-data.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
    {{- if not (eq (toString .Values.actuator.port) "http") }}
    - name: actuator
      port: {{ .Values.actuator.port }}
      targetPort: actuator
      protocol: TCP
      {{- end }}
  selector:
    {{- include "laa-crime-equinity-historical-data.selectorLabels" . | nindent 4 }}
