{{- if .Values.actuator.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Chart.Name }}-monitoring
  namespace: {{ .Chart.Name }}-{{ .Values.service.environment }}
spec:
  selector:
    matchLabels:
      {{- include "laa-crime-equinity-historical-data.selectorLabels" . | nindent 6 }}
  endpoints:
    {{- if not (eq (toString .Values.actuator.port) "http") }}
    - port: actuator
    {{- else }}
    - port: http
    {{- end }}
      interval: {{ .Values.actuator.metrics.scrapeInterval }}
      path: {{ .Values.actuator.metrics.path }}
{{- end }}