name: 'Build App with Gradle'
description: 'This action builds application jar using Gadle'
inputs:
  java-version:
    required: true
    type: string
  java-dist:
    required: true
    type: string
  working-directory:
    required: true
    type: string

steps:
  - uses: actions/checkout@v4

  - name: Set up JDK ${{env.JAVA_VERSION}}
    uses: actions/setup-java@v4
    with:
      java-version: ${{inputs.java-version}}
      distribution: ${{inputs.java-dist}}

  - name: Setup Gradle
    uses: gradle/gradle-build-action@v2
    with:
      build-root-directory: ${{inputs.working-directory}}

  - name: Build and install dependencies
    uses: gradle/gradle-build-action@v2
    with:
      arguments: clean build
      build-root-directory: ${{inputs.working-directory}}
