# Default values for laa-crime-equinity-historical-data.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  # Override the image repository whose real value should come from secret.
  repository: ""
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

securityContext:
  runAsNonRoot: true
  readOnlyRootFilesystem: false


service:
  type: ClusterIP
  port: 8089
  environment: "uat"

database:
  name: "eq_uat"

ingress:
  enabled: true
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: "laa-crime-equinity-historical-data-ingress-laa-crime-equinity-historical-data-uat-green"
    external-dns.alpha.kubernetes.io/aws-weight: "100"
