# Default values for laa-crime-equinity-historical-data.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  # Override the image repository whose real value should come from secret.
  repository: ""
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

service:
  port: 8089
  environment: "archive"

securityContext:
  runAsNonRoot: true
  readOnlyRootFilesystem: false
  runAsUser: 10001

database:
  name: "eq_archive"

ingress:
  enabled: true
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: "laa-crime-equinity-historical-data-ingress-laa-crime-equinity-historical-data-archive-green"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "120"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "120"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
    nginx.ingress.kubernetes.io/proxy-body-size: 16m

