# Default values for laa-crime-equinity-historical-data.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  # Override the image repository whose real value should come from secret.
  repository: ""
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8089
  environment: "uat"

ingress:
  enabled: true
  className: default
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: "laa-crime-equinity-historical-data-ingress-laa-crime-equinity-historical-data-uat-green"
    external-dns.alpha.kubernetes.io/aws-weight: "100"
