openapi: '3.0.0'
info:
  title: 'Equinity-data-api'
  version: '1.0.0'
paths:
  /api/internal/v1/equinity/search/:
    get:
      tags:
        - search
        - CRM
        - tasks
      summary: 'Search CRM forms'
      operationId: 'doSearchBy'
      parameters:
        - name: 'usn'
          in: 'query'
          required: false
          schema:
            type: string
            example: '3456'
            minLength: 3
            maxLength: 10
            pattern: '[0-9]{3,10}'
        - name: 'client'
          description: 'Client name'
          in: 'query'
          required: false
          schema:
            type: string
            example: 'John Doe'
            minLength: 3
            maxLength: 256
        - name: 'clientDoB'
          in: 'query'
          required: false
          schema:
            type: string
            pattern: "^[0-9]{4}-(1[0-2]|0[1-9])-(3[01]|[12][0-9]|0[1-9])$"
            example: '2023-01-31'
        - name: 'submittedFrom'
          in: 'query'
          required: false
          schema:
            type: string
            pattern: "^[0-9]{4}-(1[0-2]|0[1-9])-(3[01]|[12][0-9]|0[1-9])$"
            example: '2019-03-18'

        - name: 'submittedTo'
          in: 'query'
          required: false
          schema:
            type: string
            pattern: "^[0-9]{4}-(1[0-2]|0[1-9])-(3[01]|[12][0-9]|0[1-9])$"
            example: '2019-04-13'

        - name: 'providerAccount'
          in: 'query'
          required: false
          schema:
            type: string
            minLength: 6
            maxLength: 6
            pattern: "([0-9A-Za-z]){6}"
            example: '0X12YZ'
      responses:
        '200':
          description: 'Success'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CrmFormsDTO"
        '400':
          description: 'Bad request'
        '401':
          description: 'Unauthorized'
        '404':
          description: 'Not found'
        '500':
          description: 'Internal server error'

  /crm5/{usn}:
    get:
      tags:
        - CRM5Interface
      operationId: getApplication
      parameters:
        - name: usn
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CRM5DetailsDTO'
                
  /equinity/tasks/{id}:
    get:
      tags:
        - tasks
      summary: 'Get Task'
      operationId: 'getTask'
      parameters:
        - name: 'id'
          in: 'path'
          required: true
          schema:
            type: number
            example: '3456'
      responses:
        '200':
          description: 'Successful operation'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TaskDetails"
        '400':
          description: 'Bad request'
        '401':
          description: 'Unauthorized'
        '404':
          description: 'Not found'
        '500':
          description: 'Internal server error'

components:
  schemas:
    CrmFormsDTO:
      type: 'object'
      readOnly: true
      properties:
        usn:
          type: number
        type:
          type:
            string
        clientName:
          type: string
        originatedDate:
          type: string
        submittedDate:
          type: string
        providerAccount:
          type: string
        providerName:
          type: string

    CRM5DetailsDTO:
      type: object
      properties:
        usn:
          type: integer
        hasPreviousApplication:
          type: boolean
        previousApplicationRef:
          type: string
        appealedPrevDecision:
          type: boolean
        appealedPrevDecisionDetails:
          type: string
        urgent:
          type: boolean
        urgencyReason:
          type: string
          enum:
            - Urgent preparation prior to interview of client
            - HMP has limited visiting times/or has a cancellation
            - Deadline for representations imminent
            - Late notification of adjudication/oral/paper hearing
            - Urgent healthcare issues e.g. hospitalisation
            - Deadline for submitting appeal
            - Urgent HMP visit
            - Application returned as incomplete hence delayed
            - Brief Counsel/Expert tight time frame
            - Additional costs e.g. client transferred HMP short notice
            - Information required urgently by CCRC
        StatementOfCase:
          type: string
        DetailsOfWorkCompleted:
          type: string
        DetailsOfApplication:
          type: string

    TaskDetails:
      type: 'object'
      properties:
        typeId:
          type: number
        stateId:
          type: number
        currentParticipant:
          type: 'string'