openapi: '3.0.0'
info:
  title: 'Equinity-data-api'
  version: '1.0.0'
paths:
  /api/internal/v1/equinity/search/:
    get:
      tags:
        - Search
        - CRM
        - tasks
      summary: 'Search CRM forms'
      operationId: 'doSearchBy'
      parameters:
        - name: 'usn'
          in: 'query'
          required: false
          schema:
            type: string
            example: '3456'
            minLength: 3
            maxLength: 10
            pattern: '[0-9]{3,10}'
        - name: 'client'
          description: 'Client name'
          in: 'query'
          required: false
          schema:
            type: string
            example: 'John Doe'
            minLength: 3
            maxLength: 256
        - name: 'clientDoB'
          in: 'query'
          required: false
          schema:
            type: string
            pattern: "^[0-9]{4}-(1[0-2]|0[1-9])-(3[01]|[12][0-9]|0[1-9])$"
            example: '2023-01-31'
        - name: 'submittedFrom'
          in: 'query'
          required: false
          schema:
            type: string
            pattern: "^[0-9]{4}-(1[0-2]|0[1-9])-(3[01]|[12][0-9]|0[1-9])$"
            example: '2019-03-18'

        - name: 'submittedTo'
          in: 'query'
          required: false
          schema:
            type: string
            pattern: "^[0-9]{4}-(1[0-2]|0[1-9])-(3[01]|[12][0-9]|0[1-9])$"
            example: '2019-04-13'

        - name: 'providerAccount'
          in: 'query'
          required: false
          schema:
            type: string
            minLength: 6
            maxLength: 6
            pattern: "([0-9A-Za-z]){4,6}"
            example: '0X12YZ'
        - name: 'page'
          in: 'query'
          required: false
          schema:
            default: 0
            type: integer
            minimum: 0
            example: 0
        - name: 'perPage'
          in: 'query'
          required: false
          schema:
            default: 10
            type: integer
            minimum: 10
            maximum: 100
            example: 20
      responses:
        '200':
          description: 'Success'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SearchDTO"
        '400':
          description: 'Bad request'
        '401':
          description: 'Unauthorized'
        '404':
          description: 'Not found'
        '500':
          description: 'Internal server error'

  /crm5/{usn}:
    get:
      tags:
        - CRM5Interface
      operationId: getApplication
      parameters:
        - name: usn
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CRM5DetailsDTO'
  ###
  # Archive
  ###
  /api/internal/v1/equinity/archive/search/:
    get:
      tags:
        - Search Archive
        - search
        - CRM
        - tasks
      summary: 'Search Archive for CRM forms'
      operationId: 'doSearchArchiveBy'
      parameters:
        - name: 'usn'
          in: 'query'
          required: false
          schema:
            type: string
            example: '3456'
            minLength: 3
            maxLength: 10
            pattern: '[0-9]{3,10}'
        - name: 'client'
          description: 'Client name'
          in: 'query'
          required: false
          schema:
            type: string
            example: 'John Doe'
            minLength: 3
            maxLength: 256
        - name: 'clientDoB'
          in: 'query'
          required: false
          schema:
            type: string
            pattern: "^[0-9]{4}-(1[0-2]|0[1-9])-(3[01]|[12][0-9]|0[1-9])$"
            example: '2023-01-31'
        - name: 'submittedFrom'
          in: 'query'
          required: false
          schema:
            type: string
            pattern: "^[0-9]{4}-(1[0-2]|0[1-9])-(3[01]|[12][0-9]|0[1-9])$"
            example: '2019-03-18'

        - name: 'submittedTo'
          in: 'query'
          required: false
          schema:
            type: string
            pattern: "^[0-9]{4}-(1[0-2]|0[1-9])-(3[01]|[12][0-9]|0[1-9])$"
            example: '2019-04-13'

        - name: 'providerAccount'
          in: 'query'
          required: false
          schema:
            type: string
            minLength: 6
            maxLength: 6
            pattern: "([0-9A-Za-z]){4,6}"
            example: '0X12YZ'
        - name: 'page'
          in: 'query'
          required: false
          schema:
            default: 0
            type: integer
            minimum: 0
            example: 0
        - name: 'perPage'
          in: 'query'
          required: false
          schema:
           default: 10
           type: integer
           minimum: 10
           maximum: 100
           example: 20
      responses:
        '200':
          description: 'Success'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SearchDTO"
        '400':
          description: 'Bad request'
        '401':
          description: 'Unauthorized'
        '404':
          description: 'Not found'
        '500':
          description: 'Internal server error'

components:
  schemas:
    SearchDTO:
      type: 'object'
      properties:
        searchResultsDTO:
          type: array
          items:
            $ref: "#/components/schemas/CrmFormsDTO"
        page:
          type: integer
        perPage:
          type: integer
        totalPages:
          type: integer
        totalRecords:
          type: number

    CrmFormsDTO:
      type: 'object'
      readOnly: true
      properties:
        usn:
          type: number
        type:
          type:
            string
        clientName:
          type: string
        originatedDate:
          type: string
        submittedDate:
          type: string
        providerAccount:
          type: string
        providerName:
          type: string

    CRM5DetailsDTO:
      type: object
      properties:
        usn:
          type: integer
        hasPreviousApplication:
          type: string
        previousApplicationRef:
          type: string
        appealedPrevDecision:
          type: string
        appealedPrevDecisionDetails:
          type: string
        urgent:
          type: string
        urgencyReason:
          type: string
        Firm:
          $ref: '#/components/schemas/Firm'
        CaseDetails:
          $ref: '#/components/schemas/CaseDetails'
        ClientDetails:
          $ref: '#/components/schemas/ClientDetails'
        Proceedings:
          $ref: '#/components/schemas/Proceedings'
        StatementOfCase:
          type: string
        DetailsOfWorkCompleted:
          type: string
        DetailsOfApplication:
          type: string

    TaskDetails:
      type: 'object'
      properties:
        typeId:
          type: number
        stateId:
          type: number
        currentParticipant:
          type: 'string'
    Firm:
      type: object
      properties:
        firmAddress:
          type: string
        firmName:
          type: string
        firmPhone:
          type: string
        firmSupplierNo:
          type: string
        firmContactName:
          type: string
        firmSolicitorName:
          type: string
        firmSolicitorRef:
          type: string
    CaseDetails:
      type: object
      properties:
        levelOfWork:
          type: string
        cwCriminalInvestigation:
          type: boolean
        cwCcrc:
          type: boolean
        cwAppealsReview:
          type: boolean
        cwPrisonLaw:
          type: boolean
    ClientDetails:
      type: object
      properties:
        UFN:
          type: string
        firstName:
          type: string
        middleName:
          type: string
        surname:
          type: string
        maritalStatus:
          type: string
        dateOfBirth:
          type: string
          format: date-time
        nationalInsuranceNumber:
          type: string
        address:
          $ref: '#/components/schemas/Address'
    Address:
      type: object
      properties:
        noFixedAbode:
          type: boolean
        postcode:
          type: string
        addressLine1:
          type: string
        addressLine2:
          type: string
        addressLine3:
          type: string
        city:
          type: string
        county:
          type: string
        country:
          type: string
    Proceedings:
      type: object
      properties:
        TypeOfProceedings:
          $ref: '#/components/schemas/TypeOfProceedings'
        DetailsOfProceedings:
          $ref: '#/components/schemas/DetailsOfProceedings'
    TypeOfProceedings:
      type: object
      properties:
        preCharge:
          type: string
        appealProceedings:
          type: string
        prisonLaw:
          type: string
    DetailsOfProceedings:
      type: object
      properties:
        dateOfNextHearing:
          type: string
          format: date-time
        isCounselInstructed:
          type: string