openapi: '3.0.0'
info:
  title: 'Equinity-data-api'
  version: '1.0.0'
paths:
  /api/internal/v1/equinity/search/:
    get:
      tags:
        - Search
        - CRM
        - tasks
      summary: 'Search CRM forms'
      operationId: 'doSearchBy'
      parameters:
        - name: 'usn'
          in: 'query'
          required: false
          schema:
            type: string
            example: '3456'
            minLength: 3
            maxLength: 10
            pattern: '[0-9]{3,10}'
        - name: 'client'
          description: 'Client name'
          in: 'query'
          required: false
          schema:
            type: string
            example: 'John Doe'
            minLength: 3
            maxLength: 256
        - name: 'clientDoB'
          in: 'query'
          required: false
          schema:
            type: string
            pattern: "^[0-9]{4}-(1[0-2]|0[1-9])-(3[01]|[12][0-9]|0[1-9])$"
            example: '2023-01-31'
        - name: 'submittedFrom'
          in: 'query'
          required: false
          schema:
            type: string
            pattern: "^[0-9]{4}-(1[0-2]|0[1-9])-(3[01]|[12][0-9]|0[1-9])$"
            example: '2019-03-18'

        - name: 'submittedTo'
          in: 'query'
          required: false
          schema:
            type: string
            pattern: "^[0-9]{4}-(1[0-2]|0[1-9])-(3[01]|[12][0-9]|0[1-9])$"
            example: '2019-04-13'

        - name: 'providerAccount'
          in: 'query'
          required: false
          schema:
            type: string
            minLength: 6
            maxLength: 6
            pattern: "([0-9A-Za-z]){4,6}"
            example: '0X12YZ'
        - name: 'page'
          in: 'query'
          required: false
          schema:
            default: 0
            type: integer
            minimum: 0
            example: 0
        - name: 'pageSize'
          in: 'query'
          required: false
          schema:
            default: 10
            type: integer
            minimum: 10
            maximum: 100
            example: 20
      responses:
        '200':
          description: 'Success'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SearchResultDTO"
        '400':
          description: 'Bad request'
        '401':
          description: 'Unauthorized'
        '404':
          description: 'Not found'
        '500':
          description: 'Internal server error'

  /api/internal/v1/equinity/crm5/{usn}:
    get:
      tags:
        - CRM5Interface
      operationId: getApplication
      parameters:
        - name: usn
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CRM5DetailsDTO'
  ###
  # Archive
  ###
  /api/internal/v1/equinity/archive/search/:
    get:
      tags:
        - Search Archive
        - search
        - CRM
        - tasks
      summary: 'Search Archive for CRM forms'
      operationId: 'doSearchArchiveBy'
      parameters:
        - name: 'usn'
          in: 'query'
          required: false
          schema:
            type: string
            example: '3456'
            minLength: 3
            maxLength: 10
            pattern: '[0-9]{3,10}'
        - name: 'client'
          description: 'Client name'
          in: 'query'
          required: false
          schema:
            type: string
            example: 'John Doe'
            minLength: 3
            maxLength: 256
        - name: 'clientDoB'
          in: 'query'
          required: false
          schema:
            type: string
            pattern: "^[0-9]{4}-(1[0-2]|0[1-9])-(3[01]|[12][0-9]|0[1-9])$"
            example: '2023-01-31'
        - name: 'submittedFrom'
          in: 'query'
          required: false
          schema:
            type: string
            pattern: "^[0-9]{4}-(1[0-2]|0[1-9])-(3[01]|[12][0-9]|0[1-9])$"
            example: '2019-03-18'

        - name: 'submittedTo'
          in: 'query'
          required: false
          schema:
            type: string
            pattern: "^[0-9]{4}-(1[0-2]|0[1-9])-(3[01]|[12][0-9]|0[1-9])$"
            example: '2019-04-13'

        - name: 'providerAccount'
          in: 'query'
          required: false
          schema:
            type: string
            minLength: 6
            maxLength: 6
            pattern: "([0-9A-Za-z]){4,6}"
            example: '0X12YZ'
        - name: 'page'
          in: 'query'
          required: false
          schema:
            default: 0
            type: integer
            minimum: 0
            example: 0
        - name: 'pageSize'
          in: 'query'
          required: false
          schema:
           default: 10
           type: integer
           minimum: 10
           maximum: 100
           example: 20
      responses:
        '200':
          description: 'Success'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SearchResultDTO"
        '400':
          description: 'Bad request'
        '401':
          description: 'Unauthorized'
        '404':
          description: 'Not found'
        '500':
          description: 'Internal server error'

components:
  schemas:
    SearchResultDTO:
      type: 'object'
      properties:
        results:
          type: array
          items:
            $ref: "#/components/schemas/SearchCrmFormDTO"
        paging:
          $ref: '#/components/schemas/SearchPagingDTO'
    SearchCrmFormDTO:
      type: 'object'
      readOnly: true
      properties:
        usn:
          type: number
        type:
          type:
            string
        clientName:
          type: string
        originatedDate:
          type: string
        submittedDate:
          type: string
        providerAccount:
          type: string
        providerName:
          type: string
    SearchPagingDTO:
      type: 'object'
      readOnly: true
      properties:
        size:
          type: integer
        number:
          type: integer
        total:
          type: integer
        itemsPage:
          type: integer
        itemsTotal:
          type: number

    CRM5DetailsDTO:
      type: object
      properties:
        usn:
          type: integer
        hasPreviousApplication:
          type: string
        previousApplicationRef:
          type: string
        appealedPrevDecision:
          type: string
        appealedPrevDecisionDetails:
          type: string
        urgent:
          type: string
        urgencyReason:
          type: string
        Firm:
          $ref: '#/components/schemas/Crm5FirmDTO'
        CaseDetails:
          $ref: '#/components/schemas/Crm5CaseDetailsDTO'
        ClientDetails:
          $ref: '#/components/schemas/Crm5ClientDTO'
        CapitalDetails:
          $ref: '#/components/schemas/Crm5CapitalDTO'
        IncomeDetails:
          $ref: '#/components/schemas/Crm5IncomeDTO'
        Proceedings:
          $ref: '#/components/schemas/Crm5ProceedingsDTO'
        CourtAppealFunding:
          $ref: '#/components/schemas/Crm5AppealFundingDTO'
        AllCosts:
          $ref: '#/components/schemas/Crm5AllCostsDTO'
        CaseHistory:
          $ref: '#/components/schemas/Crm5CaseHistoryDTO'
        Solicitor:
          $ref: '#/components/schemas/Crm5SolicitorDTO'
        OfficeUseOnly:
          $ref: '#/components/schemas/Crm5DecisionDTO'
        StatementOfCase:
          type: string
        DetailsOfWorkCompleted:
          type: string
        DetailsOfApplication:
          type: string
    Crm5FirmDTO:
      type: object
      properties:
        firmAddress:
          type: string
        firmName:
          type: string
        firmPhone:
          type: string
        firmSupplierNo:
          type: string
        firmContactName:
          type: string
        firmSolicitorName:
          type: string
        firmSolicitorRef:
          type: string
    Crm5CaseDetailsDTO:
      type: object
      properties:
        levelOfWork:
          type: string
        cwCriminalInvestigation:
          type: boolean
        cwCcrc:
          type: boolean
        cwAppealsReview:
          type: boolean
        cwPrisonLaw:
          type: boolean
    Crm5ClientDTO:
      type: object
      properties:
        UFN:
          type: string
        firstName:
          type: string
        middleName:
          type: string
        surname:
          type: string
        maritalStatus:
          type: string
        dateOfBirth:
          type: string
          format: date-time
        nationalInsuranceNumber:
          type: string
        address:
          $ref: '#/components/schemas/Crm5AddressDTO'
    Crm5AddressDTO:
      type: object
      properties:
        noFixedAbode:
          type: boolean
        postcode:
          type: string
        addressLine1:
          type: string
        addressLine2:
          type: string
        addressLine3:
          type: string
        city:
          type: string
        county:
          type: string
        country:
          type: string
    Crm5ProceedingsDTO:
      type: object
      properties:
        TypeOfProceedings:
          $ref: '#/components/schemas/Crm5TypeOfProceedingsDTO'
        DetailsOfProceedings:
          $ref: '#/components/schemas/Crm5DetailsOfProceedingsDTO'
    Crm5TypeOfProceedingsDTO:
      type: object
      properties:
        preCharge:
          type: string
        appealProceedings:
          type: string
        prisonLaw:
          type: string
    Crm5DetailsOfProceedingsDTO:
      type: object
      properties:
        dateOfNextHearing:
          type: string
          format: date-time
        isCounselInstructed:
          type: string
    Crm5CapitalDTO:
      type: object
      properties:
        isUnder18:
          type: string
        hasIncomeSupport:
          type: string
          description: Does client or partner get income support
        numOfDependants:
          type: integer
          format: int32
        clientSavings:
          type: integer
          format: int32
        partnerSavings:
          type: integer
          format: int32
        totalSavings:
          type: integer
          format: int32
    Crm5IncomeDTO:
      type: object
      properties:
        hasIncomeSupport:
          type: boolean
          description: Does client or partner get income support
        weeklyClientIncome:
          type: integer
          format: int32
        weeklyPartnerIncome:
          type: integer
          format: int32
        weeklyIncomeWithoutDeduction:
          type: integer
          format: int32
        incomeTaxDeductions:
          type: integer
          format: int32
        niDeductions:
          type: integer
          format: int32
        partnerDeductions:
          type: integer
          format: int32
        socialFundDeductions:
          type: integer
          format: int32
        dependantChildrenUnder15:
          type: integer
          format: int32
          description: Number of dependant children under 15 years
        deductionUnder15:
          type: integer
          format: int32
        dependantChildrenOver16:
          type: integer
          format: int32
        deductionOver16:
          type: integer
          format: int32
        totalDeductions:
          type: integer
          format: int32
        totalWeeklyIncome:
          type: integer
          format: int32
    Crm5AppealFundingDTO:
      type: object
      properties:
        hasCourtAppeal:
          type: boolean
        appealDetails:
          type: string
        benefitOfCourt:
          type: boolean
        expertReport:
          type: boolean
    Crm5AllCostsDTO:
      type: object
      properties:
        AccruedCosts:
          $ref: '#/components/schemas/Crm5AccruedCostsDTO'
        AnticipatedCosts:
          $ref: '#/components/schemas/Crm5AnticipateCostsDTO'
        NewLimitRequest:
          $ref: '#/components/schemas/Crm5CostOnlyDTO'
    Crm5AccruedCostsDTO:
      type: object
      properties:
        Attendance:
          $ref: '#/components/schemas/Crm5TimeCostDTO'
        Preparation:
          $ref: '#/components/schemas/Crm5TimeCostDTO'
        Advocacy:
          $ref: '#/components/schemas/Crm5TimeCostDTO'
        Travel:
          $ref: '#/components/schemas/Crm5TimeCostDTO'
        Waiting:
          $ref: '#/components/schemas/Crm5TimeCostDTO'
        Letters:
          $ref: '#/components/schemas/Crm5GeneralCostDTO'
        TelephoneCalls:
          $ref: '#/components/schemas/Crm5GeneralCostDTO'
        Mileage:
          $ref: '#/components/schemas/Crm5GeneralCostDTO'
        OtherDisbursement:
          $ref: '#/components/schemas/Crm5CostOnlyDTO'
        TotalCost:
          $ref: '#/components/schemas/Crm5CostOnlyDTO'
    Crm5AnticipateCostsDTO:
      type: object
      properties:
        Attendance:
          $ref: '#/components/schemas/Crm5TimeCostDTO'
        Preparation:
          $ref: '#/components/schemas/Crm5TimeCostDTO'
        Advocacy:
          $ref: '#/components/schemas/Crm5TimeCostDTO'
        Travel:
          $ref: '#/components/schemas/Crm5TimeCostDTO'
        Waiting:
          $ref: '#/components/schemas/Crm5TimeCostDTO'
        Letters:
          $ref: '#/components/schemas/Crm5GeneralCostDTO'
        TelephoneCalls:
          $ref: '#/components/schemas/Crm5GeneralCostDTO'
        Mileage:
          $ref: '#/components/schemas/Crm5GeneralCostDTO'
        OtherDisbursement:
          $ref: '#/components/schemas/Crm5CostOnlyDTO'
        TotalCost:
          $ref: '#/components/schemas/Crm5CostOnlyDTO'
    Crm5TimeCostDTO:
      type: object
      properties:
        time:
          type: string
          format: time
          description: only Time in 24 hrs format HH:MM
        cost:
          type: number
          format: float
    Crm5GeneralCostDTO:
      type: object
      properties:
        total:
          type: number
          format: float
        cost:
          type: number
          format: float
    Crm5CostOnlyDTO:
      properties:
        cost:
          type: number
          format: float
          description: Displayed along with currency symbol e.g £950.00
    Crm5CaseHistoryDTO:
      type: object
      properties:
        summary:
          type: string
        addtionalInfo:
          type: string
    Crm5SolicitorDTO:
      type: object
      properties:
        declaration:
          $ref: '#/components/schemas/Crm5NameAndDateDTO'
        certification:
          $ref: '#/components/schemas/Crm5NameAndDateDTO'
    Crm5NameAndDateDTO:
      type: object
      properties:
        date:
          type: string
          format: date-time
        name:
          type: string
    Crm5DecisionDTO:
      properties:
        decision:
          type: string
          description: Grant, Part Grant, Reject, Refer For ICA
