spring:
  jackson:
    default-property-inclusion: NON_NULL
  mvc:
    format:
      date: dd-MM-yyyy
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://${DB_ENDPOINT};encrypt=true;trustServerCertificate=true;databaseName=${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: 'true'
    show-sql: ${DB_DEBUG}
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

springdoc:
  packagesToScan: uk.gov.justice.laa.crime.equinity.historicaldata
  show-actuator: true
  api-docs:
    path: /api-docs
    enabled: false
  swagger-ui:
    path: /swagger-ui
    enabled: false

server:
  port: 8089
  api:
    url-path: /api/internal/v1/equinity
    pageSize: 20
  security:
    client-id:
      header: EQ-API-CLIENT-ID
      secret: ${EQ_OAUTH_CLIENT_ID}
    client-secret:
      header: EQ-API-SECRET
      secret: ${EQ_OAUTH_CLIENT_SECRET}

management:
  server:
    port: 8188
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus


sentry:
  debug: off
  dsn: ${SENTRY_DSN}
  # With a sample rate of 1, all traffic will be sent to Sentry
  traces-sample-rate: 0.50
  environment: ${HOST_ENV}
  release: 1.0.0
  servername: aws-eks-container
  send-default-pii: true
  attach-stacktrace: true
  # With a sample rate of 1, all traffic will be sent to Sentry
  sample-rate: 0.80
  logging:
    minimum-event-level: warn
    minimum-breadcrumb-level: info
  in-app-includes: uk.gov.justice.laa.crime.equinity.historicaldata
