spring:
  jackson:
    default-property-inclusion: NON_NULL
  mvc:
    format:
      date: dd-MM-yyyy
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://${DB_ENDPOINT};encrypt=true;trustServerCertificate=true;databaseName=${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: 'true'
    show-sql: ${DB_DEBUG}

    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  security:
    oauth2:
      client:
#        provider:
#          equiniti:
#            token-uri: ${EQ_OAUTH_URL}
        registration:
          equiniti:
            client-id: ${EQ_OAUTH_CLIENT_ID}
            client-secret: ${EQ_OAUTH_CLIENT_SECRET}
            authorization-grant-type: client_credentials
#            scope:
#              - ${EQ_OAUTH_SCOPE}
#      resource-server:
#        jwt:
#          issuer-uri: ${LAA_EQ_RESOURCE_SERVER_ISSUER_URI}

server:
  port: 8089

management:
  server:
    port: 8188
  endpoints:
    web:
      exposure:
        include: health,info,metrics