spring:
  jackson:
    default-property-inclusion: NON_NULL
  mvc:
    format:
      date: dd-MM-yyyy
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://${DB_ENDPOINT};encrypt=true;trustServerCertificate=true;databaseName=${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: 'true'
    show-sql: ${DB_DEBUG}

    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

datasource:
  archive:
    table: CrmFormsView
    catalog: eq_archive
    schema: dbo

server:
  port: 8089
  api:
    url-path: /api/internal/v1/equinity
    perPage: 20
  security:
    client-id:
      header: EQ-API-CLIENT-ID
      secret: ${EQ_OAUTH_CLIENT_ID}
    client-secret:
      header: EQ-API-SECRET
      secret: ${EQ_OAUTH_CLIENT_SECRET}

management:
  server:
    port: 8188
  endpoints:
    web:
      exposure:
        include: health,info,metrics