# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Deploy after UAT

on:
  workflow_run:
    workflows: [ "Build and Deploy after PR merged" ]
    types:
      - completed

  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  capture-repo-info:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/_capture-repo-info.yml

  deploy-staging:
    permissions:
      contents: read
      packages: write
      id-token: write
    needs:
      - capture-repo-info
    runs-on: ubuntu-latest
    environment: "staging"

    steps:
      - run: |
          echo "Coming soon"
          echo "image_tag: [[ ${{ env.IMAGE_TAG }} ]]"
        env:
          IMAGE_TAG: ${{ needs.capture-repo-info.outputs.repo_name }}-${{ github.sha }} # Tags ECR image with commit sha

  deploy-prod:
    permissions:
      contents: read
      packages: write
      id-token: write
    needs:
      - deploy-staging
      - capture-repo-info
    runs-on: ubuntu-latest
    environment: "prod"
    steps:
      - run: |
          echo "Coming soon"
          echo "image_tag: [ [ ${ { env.IMAGE_TAG } } ] ]"
        env:
          IMAGE_TAG: ${{ needs.capture-repo-info.outputs.repo_name }}-${{ github.sha }} # Tags ECR image with commit sha
