# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Collect repo info and app name

on:
  workflow_call:
env:
  JAVA_VERSION: 17
  JAVA_DIST: temurin

permissions:
  contents: read
  packages: write

jobs:
  collect-info:
    runs-on: ubuntu-latest
    # map a step output to job output
    outputs:
      repo_name: ${{ steps.collect-info.outputs.repo_name }}
      app_name: ${{ steps.collect-info.outputs.app_name }}
      working_directory: "./${{ steps.collect-info.outputs.repo_name }}"

    steps:
      - name: Extract short repo name
        shell: bash
        run: echo "repo_name=${GITHUB_REPOSITORY#*\/laa-crime-}" >> $GITHUB_OUTPUT
        id: extract_repo_name

      - name: Extract app name name
        shell: bash
        run: echo "app_name=${GITHUB_REPOSITORY#ministryofjustice\/}" >> $GITHUB_OUTPUT
        id: extract_app_name
