# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle
name: Unit-Tests on pushed branch

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
env:
  JAVA_VERSION: 17
  JAVA_DIST: temurin

permissions:
  contents: read
  packages: write


jobs:
  capture-repo-info:
    uses: ./.github/workflows/_capture-repo-info.yml

  build:
    runs-on: ubuntu-latest
    needs:
      - capture-repo-info

    steps:
      - uses: actions/checkout@v4
      - name: Build app jar with gradle
        uses: './.github/actions/build-app-gradle'
        with:
          java-version: ${{env.JAVA_VERSION}}
          java-dist: ${{env.JAVA_DIST}}
      # Snyk
      - name: Run Snyk to check app for vulnerabilities
        uses: snyk/actions/gradle@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: |
            --all-sub-projects  
            --severity-threshold=high  
            --sarif-file-output=snyk.sarif
      - name: Upload app scan results to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif

#  snyk:
#    runs-on: ubuntu-latest
#    needs: build
#    permissions: write-all
#
#    steps:
#      - uses: actions/checkout@v4
#      - name: Run Snyk to check app for vulnerabilities
#        uses: snyk/actions/gradle@master
#        continue-on-error: true # To make sure that SARIF upload gets called
#        env:
#          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
#        with:
#          args: |
#            --all-sub-projects
#            --severity-threshold=high
#            --sarif-file-output=snyk.sarif
#      - name: Upload app scan results to GitHub Code Scanning
#        uses: github/codeql-action/upload-sarif@v3
#        with:
#          sarif_file: snyk.sarif

#  test:
#    runs-on: ubuntu-latest
#    needs:
#      - capture-repo-info
#
#    steps:
#      - uses: actions/checkout@v4
#
#      - name: Run unit tests with gradle
#        uses: './.github/actions/test-app-gradle'
#        with:
#          java-version: ${{env.JAVA_VERSION}}
#          java-dist: ${{env.JAVA_DIST}}
